# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eab22a7504f6de17e05c6007b1b7be826efa583c98fa889cc05cd3f9baa812e08a2aae527c7f1ee230dfabdb059471a06fb802b5abf95ab532ca8940288549ef

test:
  secret_key_base: 8925205ec893a23462b6f4607e28e9c1ec0e8f8e20c68f8df032727d41498db71f3559670f10f04e9cd461dde20cc4d9457d5047db0cbfd0caaee5b6c71a16a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
